# Load distro-specific variables
# based of and edited for Ubuntu 20.04
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
- include_vars: "{{ ansible_distribution }}.yml"

# Install aptitude package tool
#- name: Install aptitude using apt
#  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

# Install docker dependencies 
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

# Add Docker’s official GPG key
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Set up the official stable repository of Docker
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install docker Engine
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

# Add the docker mudule so that ansible can manage Docker
- name: Install Docker Module for Python
  pip:
    name: docker

# Set up default container (Ubuntu)
- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

# Creates the number of containers defined by the variable create_containers, using values from vars file
- name: Create default containers
  docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    state: present
  with_sequence: count={{ create_containers }}