# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# Main of docker_servers
- block:
  - import_tasks: docker_ubuntu.yml
    when: ansible_distribution == "Ubuntu"
  - import_tasks: docker_debian.yml
    when: ansible_distribution == "Debian"