# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
  
# Main of file_servers
- name: install samba package
  tags: samba
  package:
    name: samba
    state: latest