- name: ufw | install package
  tags: ufw
  package:
    state: latest
    name: ufw
  notify:
    - restart_ufw

# web server
- name: ufw | web server | allow http (80)
  tags: ufw
  ufw:
    comment: http
    rule: allow
    port: '80'
    proto: tcp

- name: ufw | web server | allow https
  tags: ufw
  ufw:
    comment: https
    rule: allow
    port: '443'
    proto: tcp
