# add public ssh key for personal homelab account
- name: users | ferry | add public key
  tags: dotfiles,ferry,ssh,ssh-keys,users
  authorized_key:
    user: ferry
    state: present
    key: "{{ item }}"
  with_file:
    - /home/ferry/.ssh/id_ed25519.pub

- name: users | ferry | add second public key
  tags: dotfiles,ferry,ssh,ssh-keys,users
  authorized_key:
    user: ferry
    state: present
    key: "{{ item }}"
  with_file:
    - /home/ferry/.ssh/ansible.pub