# Set up default container (Ubuntu)
- name: Software | Docker | Pull default Docker image for management with Ansible
  tags: docker_ubuntu_container
  docker_image:
    name: "{{ default_container_image }}"
    source: pull
  when: 
    - ansible_distribution == "Ubuntu"
    - docker is defined
    - docker == true
    - docker_default_container == true

# Creates the number of containers defined by the variable create_containers, using values from vars file
- name: Software | Docker | Create default containers
  tags: docker_ubuntu_container
  docker_container:
    name: "{{ docker_default_container_name }}{{ item }}"
    image: "{{ docker_default_container_image }}"
    command: "{{ docker_default_container_command }}"
    state: present
  with_sequence: count={{ docker_create_containers }}
  when: 
    - ansible_distribution == "Ubuntu"
    - docker is defined
    - docker == true
    - docker_default_container == true