# Install Maria Database package
- name: Software | MariaDB | install mariadb package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: 
    - ansible_distribution == "CentOS"
    - mariadb is defined
    - mariadb == true

# Install Maria Database package
- name: Software | MariaDB | install mariadb package (Debian and Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: 
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - mariadb is defined
    - mariadb == true

# Unistall Maria Database package
- name: Software | MariaDB | uninstall mariadb package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: absent
    purge: yes
  when: 
    - ansible_distribution == "CentOS"
    - mariadb is defined
    - mariadb == false

# Uninstall Maria Database package
- name: Software | MariaDB | uninstall mariadb package (Debian and Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: absent
    purge: yes
  when: 
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - mariadb is defined
    - mariadb == false