# Install Samba package
- name: Software | install samba package (Debian and Ubuntu)
  tags: samba
  package:
    name: samba
    state: latest
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - samba is defined
    - samba == true

# Uninstall Samba package
- name: Software | uninstall samba package (Debian and Ubuntu)
  tags: samba
  package:
    name: samba
    state: absent
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - samba is defined
    - samba == false