# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# add public ssh key for ansible homelab user
- name: users | simone | add public key
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA4EnhBiJD6ot/zkxcup0yNAN3xzzTDsRwar5eZp+Ygl ansible"

# add public ssh key for personal homelab account
- name: users | ferry | add public key
  tags: always
  authorized_key:
    user: ferry
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZb9rc8ZbCyj9s4gaJJ/G/QpXZVeiq13NymLrYIrhoY ferry default"

# update sshd file from template
- name: setup | sshd | setting up sshd based upon template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd