# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
 # install software for different roles if defined with true in host_vars file the software is installed. 
 # If it is defined with false then uninstall will be run
  - import_tasks: software/apache.yml
  - import_tasks: software/mariadb.yml
  - import_tasks: software/samba.yml

  - include_tasks: system_setup/unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true