# Install Unzip package
- name: install unzip
  package:
    name: unzip

# install Terraform Package
- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root